#! /bin/bash
if [ $1 = 'start' ]
then
    gunicorn --config gunicorn.conf app:app > logs/log 2>&1 &
elif [ $1 = 'stop' ]
then
    ps -ef | grep gunicorn | grep -v grep | awk '{print $2}' | head -n 1 | xargs kill -2
else
    echo 'error param'
fi

